version: 0.2

phases:
    install:
        commands:
            - sudo yum install -y yum-utils shadow-utils
            - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            - sudo yum install -y terraform
    build:
        commands:
            - cd infra
            - echo "Inicializando Terraform..."
            - terraform init -input=false
            - echo "Validando formato ..."
            - terraform fmt -check -recursive
            - echo "Validando configuración..."
            - terraform validate
artifacts:
    files:
        - '**/*'

  #git commit -m "Se crea buildspec para codebuild de validacion"
  #git add . 
  #git push origin main